/* Writer OS — Proyecto de Muestra Literario */

export const sampleProjectData = {
  project: {
    id: 'proj-susurro-sombras',
    title: 'El Susurro de las Sombras',
    description: 'En una ciudad costera envuelta en bruma perpetua, una joven archivista descubre una serie de cartas prohibidas que desvelan el verdadero origen de la noche sin fin.',
    type: 'novela',
    targetWordCount: 75000,
    createdAt: '2026-08-15T10:00:00.000Z',
    updatedAt: '2026-09-02T18:30:00.000Z'
  },
  chapters: [
    {
      id: 'chap-1',
      projectId: 'proj-susurro-sombras',
      title: 'Capítulo 1: La Marca de Ceniza',
      order: 0,
      summary: 'Elena descubre un manuscrito lacrado en los sótanos del Archivo Central y percibe que alguien la vigila desde las galerías altas.',
      characterIds: ['char-elena', 'char-cassian'],
      content: `<p>El frío del sótano no era el aire natural de la medianoche, sino esa clase de escarcha pétrea que solo se acumula donde la luz del sol ha sido desterrada durante siglos. Elena sostuvo la lámpara de latón con los dedos entumecidos, observando cómo la llama temblaba al compás de su propia respiración.</p>
<p>Bajo la tercera hilera de anaqueles de roble negro, allí donde los inventarios oficiales aseguraban que solo reposaban libros de contabilidad mercantil, un lomo de cuero desgastado desprendía un tenue olor a ceniza húmeda. No figuraba ningún número de serie. Ningún sello del Concilio.</p>
<p>Al pasar la yema del pulgar sobre el broche de cobre, una punzada de calor recorrió su muñeca. Era la misma sensación que su abuela describía en los cuentos de infancia: el tacto de las palabras vivas antes del Gran Ocaso.</p>
<hr>
<p>—Una archivista prudente sabría cuándo devolver un tomo a las tinieblas —dijo una voz grave a sus espaldas, emergiendo de entre las sombras del corredor.</p>
<p>Elena contuvo el aliento sin volverse de golpe. Conocía esa cadencia impecable y desprovista de emoción. Solo un hombre caminaba por los archivos prohibidos sin hacer crujir los tablones carcomidos: Lord Cassian Thorne.</p>`,
      createdAt: '2026-08-16T11:00:00.000Z',
      updatedAt: '2026-09-02T17:15:00.000Z'
    },
    {
      id: 'chap-2',
      projectId: 'proj-susurro-sombras',
      title: 'Capítulo 2: El Faro Apagado',
      order: 1,
      summary: 'Elena acude al muelle viejo en busca de Mateo Soler para descifrar las coordenadas náuticas marcadas en el pergamino.',
      characterIds: ['char-elena', 'char-mateo'],
      content: `<p>La niebla del puerto sabía a salmuera y brea quemada. Entre los mástiles esqueléticos de las goletas amarradas, la silueta del viejo faro se recortaba como un dedo acusador apuntando al firmamento vacío.</p>
<p>Elena se ajustó el cuello del abrigo y descendió los peldaños cubiertos de verdín. En la taberna del timonel tuerto, Mateo ya limpiaba un sextante de latón con aire distraído. Cuando ella dejó caer el fragmento de pergamino sobre la mesa de madera astillada, la mirada del marinero cambió de inmediato.</p>
<p>—Estas corrientes no existen en ninguna carta marina del reino —susurró él, bajando la voz hasta convertirla en un murmullo cómplice—; a menos que pretendas navegar hacia el borde mismo del mundo conocido.</p>`,
      createdAt: '2026-08-20T14:30:00.000Z',
      updatedAt: '2026-09-01T12:00:00.000Z'
    },
    {
      id: 'chap-3',
      projectId: 'proj-susurro-sombras',
      title: 'Capítulo 3: El Consejo de los Siete',
      order: 2,
      summary: 'Se desata el debate en la corte sobre los rumores de rebelión y la desaparición de registros históricos.',
      characterIds: ['char-cassian'],
      content: `<p>Las altas vidrieras del Palacio de Ópalo reflejaban únicamente la penumbra grisácea del mediodía. En torno a la mesa de obsidiana, los siete miembros del tribunal deliberaban con el ceño fruncido.</p>
<p>Cassian permaneció de pie junto al ventanal, observando el mar invisible. Sabía que el fuego encendido en los sótanos del archivo no tardaría en alcanzar las torres más altas si no actuaban con una determinación implacable.</p>`,
      createdAt: '2026-08-28T09:10:00.000Z',
      updatedAt: '2026-09-02T16:00:00.000Z'
    }
  ],
  characters: [
    {
      id: 'char-elena',
      projectId: 'proj-susurro-sombras',
      name: 'Elena Vane',
      alias: 'La Guardiana del Archivo',
      role: 'protagonista',
      description: 'Joven paleógrafa y restauradora de documentos antiguos en el Archivo Central. Observadora, tenaz e impulsada por una sed insobornable de verdad histórica.',
      notes: 'Heredó de su abuela un medallón con inscripciones en la lengua anterior al Gran Ocaso. Desconfía profundamente de las órdenes oficiales del Concilio.',
      tags: ['erudita', 'custodia', 'resistencia', 'archivo'],
      avatarColor: '#B45309',
      createdAt: '2026-08-15T12:00:00.000Z',
      updatedAt: '2026-09-02T15:00:00.000Z'
    },
    {
      id: 'char-cassian',
      projectId: 'proj-susurro-sombras',
      name: 'Lord Cassian Thorne',
      alias: 'El Silente',
      role: 'antagonista',
      description: 'Canciller de la Orden del Velo y primer consejero del tribunal. Figura enigmática de modales exquisitos y fría eficacia.',
      notes: 'Cree sinceramente que ocultar la verdad sobre el Ocaso es el único medio para preservar la paz civil y evitar la histeria colectiva.',
      tags: ['nobleza', 'canciller', 'orden del velo'],
      avatarColor: '#4F46E5',
      createdAt: '2026-08-15T12:15:00.000Z',
      updatedAt: '2026-09-01T10:00:00.000Z'
    },
    {
      id: 'char-mateo',
      projectId: 'proj-susurro-sombras',
      name: 'Mateo Soler',
      alias: 'El Cartógrafo Errante',
      role: 'secundario',
      description: 'Navegante veterano y contrabandista de mapas no autorizados. Conoce los arrecifes exteriores mejor que la guardia costera.',
      notes: 'Perdió a su hermano en una expedición hacia las aguas brumosas hace diez años; busca respuestas tanto o más que Elena.',
      tags: ['marino', 'cartografía', 'aliado'],
      avatarColor: '#059669',
      createdAt: '2026-08-16T15:00:00.000Z',
      updatedAt: '2026-08-30T18:00:00.000Z'
    },
    {
      id: 'char-silvia',
      projectId: 'proj-susurro-sombras',
      name: 'Silvia Thorne',
      alias: 'La Dama Heredera',
      role: 'secundario',
      description: 'Hermana menor de Cassian Thorne. Perteneciente al linaje noble Thorne, pero cuestiona en privado los métodos despiadados de la Orden del Velo.',
      notes: 'Mantiene correspondencia confidencial con eruditos de la academia y conoce pasajes secretos de la mansión familiar.',
      tags: ['nobleza', 'diplomacia', 'casa thorne'],
      avatarColor: '#7C3AED',
      createdAt: '2026-08-17T10:00:00.000Z',
      updatedAt: '2026-09-02T16:00:00.000Z'
    },
    {
      id: 'char-corvus',
      projectId: 'proj-susurro-sombras',
      name: 'Lord Corvus Thorne',
      alias: 'El Patriarca de Hierro',
      role: 'secundario',
      description: 'Anterior señor de la Casa Thorne y padre de Cassian y Silvia. Sentó las bases del poderío civil del linaje.',
      notes: 'Fallecido cinco años antes de los sucesos actuales. Dejó a Silvia un medallón lacrado con el emblema original.',
      tags: ['ancestro', 'linaje', 'casa thorne'],
      avatarColor: '#374151',
      createdAt: '2026-08-14T09:00:00.000Z',
      updatedAt: '2026-09-02T10:00:00.000Z'
    },
    {
      id: 'char-lucas',
      projectId: 'proj-susurro-sombras',
      name: 'Lucas Thorne',
      alias: 'El Joven Pupilo',
      role: 'secundario',
      description: 'Hijo adoptivo y pupilo de Silvia Thorne. Demuestra una asombrosa habilidad innata para el descifrado de pergaminos antiguos.',
      notes: 'Silvia lo acogió tras la revuelta de las canteras para protegerlo de la conscripción del tribunal.',
      tags: ['aprendiz', 'adopcion', 'casa thorne'],
      avatarColor: '#0284C7',
      createdAt: '2026-08-18T10:00:00.000Z',
      updatedAt: '2026-09-02T11:00:00.000Z'
    }
  ],
  groups: [
    {
      id: 'group-casa-thorne',
      projectId: 'proj-susurro-sombras',
      name: 'Casa Thorne',
      type: 'casa_noble',
      description: 'Antigua estirpe patricia encargada desde hace cuatro generaciones de la administración civil de los puertos y las finanzas del tribunal.',
      motto: 'El orden prevalece en la sombra',
      color: '#4F46E5',
      founderId: 'char-corvus',
      leaderId: 'char-cassian',
      createdAt: '2026-08-15T12:00:00.000Z',
      updatedAt: '2026-09-02T10:00:00.000Z'
    },
    {
      id: 'group-orden-velo',
      projectId: 'proj-susurro-sombras',
      name: 'Orden del Velo',
      type: 'faccion',
      description: 'Hermandad militar y judicial encargada de custodiar la censura del Gran Ocaso y mantener la obediencia en las siete provincias costeras.',
      motto: 'Silencio, custodia y rectitud',
      color: '#2563EB',
      founderId: null,
      leaderId: 'char-cassian',
      createdAt: '2026-08-15T12:30:00.000Z',
      updatedAt: '2026-09-02T11:00:00.000Z'
    },
    {
      id: 'group-gremio-mareantes',
      projectId: 'proj-susurro-sombras',
      name: 'Gremio de Mareantes del Sur',
      type: 'gremio',
      description: 'Cofradía de marinos veteranos, timoneles y constructores de goletas que desafían las prohibiciones náuticas impuestas por el Velo.',
      motto: 'Más allá del horizonte brumoso',
      color: '#059669',
      founderId: null,
      leaderId: 'char-mateo',
      createdAt: '2026-08-16T15:30:00.000Z',
      updatedAt: '2026-09-01T09:00:00.000Z'
    }
  ],
  relationships: [
    {
      id: 'rel-padre-cassian',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-corvus',
      sourceType: 'character',
      targetId: 'char-cassian',
      targetType: 'character',
      category: 'familiar',
      type: 'progenitor_descendiente',
      roleSource: 'Padre y Señor de la Casa',
      roleTarget: 'Hijo primogénito',
      isSymmetric: false,
      status: 'pasada',
      description: 'Lord Corvus instruyó a Cassian en la severidad del tribunal antes de fallecer.',
      startDate: 'Nacimiento',
      endDate: 'Año 1040',
      createdAt: '2026-08-14T10:00:00.000Z',
      updatedAt: '2026-09-02T10:00:00.000Z'
    },
    {
      id: 'rel-padre-silvia',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-corvus',
      sourceType: 'character',
      targetId: 'char-silvia',
      targetType: 'character',
      category: 'familiar',
      type: 'progenitor_descendiente',
      roleSource: 'Padre',
      roleTarget: 'Hija menor',
      isSymmetric: false,
      status: 'pasada',
      description: 'Vínculo afectuoso pero distante por las exigencias cortesanas.',
      startDate: 'Nacimiento',
      endDate: 'Año 1040',
      createdAt: '2026-08-14T10:30:00.000Z',
      updatedAt: '2026-09-02T10:00:00.000Z'
    },
    {
      id: 'rel-hermanos-thorne',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-cassian',
      sourceType: 'character',
      targetId: 'char-silvia',
      targetType: 'character',
      category: 'familiar',
      type: 'hermanos',
      roleSource: 'Hermano mayor',
      roleTarget: 'Hermana menor',
      isSymmetric: true,
      status: 'activa',
      description: 'Criados bajo la disciplina severa del linaje Thorne. Cassian procura protegerla manteniéndola al margen de los juicios del tribunal.',
      startDate: 'Desde la infancia',
      endDate: '',
      createdAt: '2026-08-17T11:00:00.000Z',
      updatedAt: '2026-09-02T12:00:00.000Z'
    },
    {
      id: 'rel-adopcion-lucas',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-silvia',
      sourceType: 'character',
      targetId: 'char-lucas',
      targetType: 'character',
      category: 'familiar',
      type: 'adopcion',
      roleSource: 'Madre adoptiva y tutora',
      roleTarget: 'Hijo adoptivo y pupilo',
      isSymmetric: false,
      status: 'activa',
      description: 'Silvia tomó bajo su amparo legal a Lucas para educarlo en la paleografía y protegerlo de las levas militares.',
      startDate: 'Año 1043',
      endDate: '',
      createdAt: '2026-08-18T10:30:00.000Z',
      updatedAt: '2026-09-02T11:00:00.000Z'
    },
    {
      id: 'rel-cassian-casa-thorne',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-cassian',
      sourceType: 'character',
      targetId: 'group-casa-thorne',
      targetType: 'group',
      category: 'pertenencia',
      type: 'pertenencia',
      roleSource: 'Patriarca y Señor de la Casa',
      roleTarget: 'Casa Noble',
      isSymmetric: false,
      status: 'activa',
      description: 'Líder titular de la dinastía tras el fallecimiento de Lord Corvus.',
      startDate: 'Año 1040',
      endDate: '',
      createdAt: '2026-08-17T11:30:00.000Z',
      updatedAt: '2026-09-02T12:00:00.000Z'
    },
    {
      id: 'rel-silvia-casa-thorne',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-silvia',
      sourceType: 'character',
      targetId: 'group-casa-thorne',
      targetType: 'group',
      category: 'pertenencia',
      type: 'pertenencia',
      roleSource: 'Heredera de linaje',
      roleTarget: 'Casa Noble',
      isSymmetric: false,
      status: 'activa',
      description: 'Miembro principal de la línea sucesoria.',
      startDate: 'Nacimiento',
      endDate: '',
      createdAt: '2026-08-17T11:35:00.000Z',
      updatedAt: '2026-09-02T12:00:00.000Z'
    },
    {
      id: 'rel-lucas-casa-thorne',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-lucas',
      sourceType: 'character',
      targetId: 'group-casa-thorne',
      targetType: 'group',
      category: 'pertenencia',
      type: 'pertenencia',
      roleSource: 'Pupilo y aprendiz de escriba',
      roleTarget: 'Casa Noble',
      isSymmetric: false,
      status: 'activa',
      description: 'Membresía tutelada bajo el patrocinio directo de la Dama Silvia.',
      startDate: 'Año 1043',
      endDate: '',
      createdAt: '2026-08-18T11:00:00.000Z',
      updatedAt: '2026-09-02T11:00:00.000Z'
    },
    {
      id: 'rel-cassian-orden-velo',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-cassian',
      sourceType: 'character',
      targetId: 'group-orden-velo',
      targetType: 'group',
      category: 'pertenencia',
      type: 'pertenencia',
      roleSource: 'Gran Canciller',
      roleTarget: 'Hermandad gobernante',
      isSymmetric: false,
      status: 'activa',
      description: 'Máxima autoridad ejecutiva del tribunal.',
      startDate: 'Año 1038',
      endDate: '',
      createdAt: '2026-08-17T12:00:00.000Z',
      updatedAt: '2026-09-02T12:00:00.000Z'
    },
    {
      id: 'rel-mateo-gremio',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-mateo',
      sourceType: 'character',
      targetId: 'group-gremio-mareantes',
      targetType: 'group',
      category: 'pertenencia',
      type: 'pertenencia',
      roleSource: 'Maestro Mayor de Rutas',
      roleTarget: 'Gremio náutico',
      isSymmetric: false,
      status: 'activa',
      description: 'Elegido por los patrones de pesca para defender los intereses del puerto frente a los decretos del palacio.',
      startDate: 'Año 1044',
      endDate: '',
      createdAt: '2026-08-17T12:15:00.000Z',
      updatedAt: '2026-09-02T12:00:00.000Z'
    },
    {
      id: 'rel-rivalidad-cassian-elena',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-cassian',
      sourceType: 'character',
      targetId: 'char-elena',
      targetType: 'character',
      category: 'social',
      type: 'rivalidad',
      roleSource: 'Canciller custodio',
      roleTarget: 'Archivista rebelde',
      isSymmetric: true,
      status: 'conflictiva',
      description: 'Choque frontal entre el deber estatal de ocultar el Gran Ocaso y la determinación de Elena por desenterrar los pergaminos perdidos.',
      startDate: 'Reciente',
      endDate: '',
      createdAt: '2026-08-18T10:00:00.000Z',
      updatedAt: '2026-09-02T13:00:00.000Z'
    },
    {
      id: 'rel-amistad-elena-mateo',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-elena',
      sourceType: 'character',
      targetId: 'char-mateo',
      targetType: 'character',
      category: 'social',
      type: 'amistad',
      roleSource: 'Investigadora',
      roleTarget: 'Piloto y guía',
      isSymmetric: true,
      status: 'activa',
      description: 'Pacto de colaboración secreta: Elena descifra mapas arcanos y Mateo la guía entre las corrientes brumosas.',
      startDate: 'Año 1047',
      endDate: '',
      createdAt: '2026-08-21T16:00:00.000Z',
      updatedAt: '2026-09-02T13:30:00.000Z'
    },
    {
      id: 'rel-orden-gremio-politica',
      projectId: 'proj-susurro-sombras',
      sourceId: 'group-orden-velo',
      sourceType: 'group',
      targetId: 'group-gremio-mareantes',
      targetType: 'group',
      category: 'politica',
      type: 'tregua',
      roleSource: 'Tribunal',
      roleTarget: 'Cofradía portuaria',
      isSymmetric: true,
      status: 'conflictiva',
      description: 'Tregua tensa: el Velo tolera la pesca costera a cambio de impuestos, pero amenaza con requisar barcos que se adentren en la niebla.',
      startDate: 'Año 1041',
      endDate: '',
      createdAt: '2026-08-22T09:00:00.000Z',
      updatedAt: '2026-09-02T14:00:00.000Z'
    },
    {
      id: 'rel-elena-archivo-laboral',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-elena',
      sourceType: 'character',
      targetId: 'place-archivo-central',
      targetType: 'place',
      category: 'social',
      type: 'trabajo',
      roleSource: 'Archivista investigadora',
      roleTarget: 'Lugar de trabajo y custodia',
      isSymmetric: false,
      status: 'activa',
      description: 'Elena pasa sus jornadas restaurando pergaminos en los sótanos prohibidos del Archivo.',
      startDate: 'Año 1045',
      endDate: '',
      createdAt: '2026-08-23T10:00:00.000Z',
      updatedAt: '2026-09-02T15:00:00.000Z'
    },
    {
      id: 'rel-cassian-puerto-gobierno',
      projectId: 'proj-susurro-sombras',
      sourceId: 'char-cassian',
      sourceType: 'character',
      targetId: 'place-puerto-gris',
      targetType: 'place',
      category: 'politica',
      type: 'gobierno',
      roleSource: 'Corregidor delegado',
      roleTarget: 'Ciudad bajo su jurisdicción',
      isSymmetric: false,
      status: 'activa',
      description: 'Supervisa el comercio, los toques de queda y las requisas de documentos en la urbe.',
      startDate: 'Año 1040',
      endDate: '',
      createdAt: '2026-08-23T10:30:00.000Z',
      updatedAt: '2026-09-02T15:30:00.000Z'
    },
    {
      id: 'rel-thorne-palacio-sede',
      projectId: 'proj-susurro-sombras',
      sourceId: 'group-casa-thorne',
      sourceType: 'group',
      targetId: 'place-palacio-opalo',
      targetType: 'place',
      category: 'politica',
      type: 'propiedad',
      roleSource: 'Linaje propietario',
      roleTarget: 'Sede y residencia solariega',
      isSymmetric: true,
      status: 'activa',
      description: 'El Palacio de Ópalo pertenece a la dinastía Thorne desde hace cuatro generaciones.',
      startDate: 'Año 980',
      endDate: '',
      createdAt: '2026-08-23T11:00:00.000Z',
      updatedAt: '2026-09-02T16:00:00.000Z'
    },
    {
      id: 'rel-puerto-faro-defensa',
      projectId: 'proj-susurro-sombras',
      sourceId: 'place-puerto-gris',
      sourceType: 'place',
      targetId: 'place-faro-niebla',
      targetType: 'place',
      category: 'politica',
      type: 'alianza',
      roleSource: 'Puerto metropolitano',
      roleTarget: 'Atalaya de defensa y aviso costero',
      isSymmetric: true,
      status: 'activa',
      description: 'El Faro de la Niebla alerta a los muelles de Puerto Gris ante incursiones navales y tormentas anómalas.',
      startDate: 'Año 910',
      endDate: '',
      createdAt: '2026-08-23T11:30:00.000Z',
      updatedAt: '2026-09-02T16:15:00.000Z'
    },
    {
      id: 'rel-rio-puerto-fluvial',
      projectId: 'proj-susurro-sombras',
      sourceId: 'place-rio-plata',
      sourceType: 'place',
      targetId: 'place-puerto-gris',
      targetType: 'place',
      category: 'social',
      type: 'otro',
      roleSource: 'Vía fluvial de suministro',
      roleTarget: 'Desembocadura portuaria',
      isSymmetric: false,
      status: 'activa',
      description: 'El Río Plata abastece de agua dulce, pesca y transporte de madera a las dársenas bajas de la ciudad.',
      startDate: 'Año 730',
      endDate: '',
      createdAt: '2026-08-23T12:00:00.000Z',
      updatedAt: '2026-09-02T16:30:00.000Z'
    },
    {
      id: 'rel-calzada-archivo-puerto',
      projectId: 'proj-susurro-sombras',
      sourceId: 'place-calzada-ocaso',
      sourceType: 'place',
      targetId: 'place-archivo-central',
      targetType: 'place',
      category: 'social',
      type: 'otro',
      roleSource: 'Vía militar y de transporte',
      roleTarget: 'Acceso fortificado superior',
      isSymmetric: false,
      status: 'activa',
      description: 'La Calzada del Gran Ocaso conecta los muelles de Puerto Gris directamente con las bóvedas del Archivo.',
      startDate: 'Año 850',
      endDate: '',
      createdAt: '2026-08-23T12:30:00.000Z',
      updatedAt: '2026-09-02T16:45:00.000Z'
    },
    {
      id: 'rel-gremio-faro-operativo',
      projectId: 'proj-susurro-sombras',
      sourceId: 'group-gremio-mareantes',
      sourceType: 'group',
      targetId: 'place-faro-niebla',
      targetType: 'place',
      category: 'social',
      type: 'trabajo',
      roleSource: 'Cofradía de prácticos',
      roleTarget: 'Atalaya y estación de señales náuticas',
      isSymmetric: false,
      status: 'activa',
      description: 'Los timoneles del Gremio coordinan con Mateo las campanas de orientación para buques mercantes.',
      startDate: 'Año 1042',
      endDate: '',
      createdAt: '2026-08-23T13:00:00.000Z',
      updatedAt: '2026-09-02T17:00:00.000Z'
    },
    {
      id: 'rel-orden-archivo-custodia',
      projectId: 'proj-susurro-sombras',
      sourceId: 'group-orden-velo',
      sourceType: 'group',
      targetId: 'place-archivo-central',
      targetType: 'place',
      category: 'politica',
      type: 'gobierno',
      roleSource: 'Tribunal censor',
      roleTarget: 'Criptas bajo custodia armada',
      isSymmetric: false,
      status: 'activa',
      description: 'Centinelas juramentados del Velo vigilan los niveles subterráneos y restringen el acceso a los códices prohibidos.',
      startDate: 'Año 1015',
      endDate: '',
      createdAt: '2026-08-23T13:30:00.000Z',
      updatedAt: '2026-09-02T17:15:00.000Z'
    }
  ],
  places: [
    {
      id: 'place-valdora',
      projectId: 'proj-susurro-sombras',
      name: 'Valdora',
      category: 'geografia',
      type: 'continente',
      parentId: null,
      description: 'Vasto continente septentrional de tierras escarpadas, bosques de tejos negros y costas azotadas por la bruma perpetua.',
      tags: ['continente', 'boreal', 'tierras-altas'],
      status: 'activo',
      history: 'Conocido antiguamente como la Cuna del Sol antes del Gran Ocaso. Hoy es el centro neurálgico del imperio fragmentado.',
      historicalDates: { foundationDate: 'Era Antigua', period: 'Tercera Edad' },
      authorities: [],
      specificData: {},
      mapData: { x: 450, y: 180, color: '#B45309' },
      color: '#B45309',
      notes: 'Territorio principal sobre el que se desarrolla toda la trama de la novela.',
      createdAt: '2026-08-15T11:00:00.000Z',
      updatedAt: '2026-09-02T14:00:00.000Z'
    },
    {
      id: 'place-oakhaven',
      projectId: 'proj-susurro-sombras',
      name: 'Reino de Oakhaven',
      category: 'geografia',
      type: 'reino',
      parentId: 'place-valdora',
      description: 'Antigua monarquía feudal de tradición marítima, actualmente administrada bajo la regencia tutelar del Concilio de las Sombras.',
      tags: ['reino', 'corona', 'regencia'],
      status: 'activo',
      history: 'Fundado tras la firma del Pacto de las Siete Banderas en el año 612.',
      historicalDates: { foundationDate: 'Año 612', period: 'Cuatro siglos de monarquía' },
      authorities: [
        {
          id: 'auth-oakhaven-cassian',
          characterId: 'char-cassian',
          title: 'Lord Canciller Regente',
          responsibilityType: 'civil',
          description: 'Ejerce la presidencia interina del consejo real en ausencia de heredero coronado.',
          startDate: 'Año 1042',
          endDate: ''
        }
      ],
      specificData: {
        capital: 'Puerto Gris',
        population: '850.000 habitantes',
        governmentSystem: 'Regencia del Concilio y Tribunal'
      },
      mapData: { x: 420, y: 220, color: '#B45309' },
      color: '#B45309',
      notes: 'La tensión dinástica amenaza con fragmentar las baronías del norte.',
      createdAt: '2026-08-15T11:15:00.000Z',
      updatedAt: '2026-09-02T14:15:00.000Z'
    },
    {
      id: 'place-costa-sombras',
      projectId: 'proj-susurro-sombras',
      name: 'Costa de las Sombras',
      category: 'geografia',
      type: 'region',
      parentId: 'place-oakhaven',
      description: 'Extensión costera bordeada por altos acantilados de roca ígnea y bahías encapotadas por neblinas densas.',
      tags: ['costa', 'litoral', 'acantilados'],
      status: 'activo',
      history: 'Escenario de naufragios legendarios y cuna de las leyendas de los Mareantes.',
      historicalDates: { foundationDate: '', period: '' },
      authorities: [],
      specificData: { region: 'Litoral Sur' },
      mapData: { x: 380, y: 310, color: '#B45309' },
      color: '#B45309',
      notes: 'Las mareas vivas de invierno cubren los accesos por tierra a las calas bajas.',
      createdAt: '2026-08-15T11:30:00.000Z',
      updatedAt: '2026-09-02T14:30:00.000Z'
    },
    {
      id: 'place-puerto-gris',
      projectId: 'proj-susurro-sombras',
      name: 'Puerto Gris',
      category: 'asentamientos',
      type: 'ciudad',
      parentId: 'place-costa-sombras',
      description: 'Principal metrópoli y puerto fortificado del reino. Calles empedradas en cuesta, muelles de madera negra y canales húmedos.',
      tags: ['ciudad', 'capital', 'puerto', 'comercio'],
      status: 'activo',
      history: 'Creció al abrigo de la bahía profunda durante el auge mercantil de la dinastía Thorne.',
      historicalDates: { foundationDate: 'Año 730', period: 'Metrópoli en crecimiento' },
      authorities: [
        {
          id: 'auth-puerto-cassian',
          characterId: 'char-cassian',
          title: 'Corregidor del Puerto',
          responsibilityType: 'civil',
          description: 'Control directo de la justicia y las aduanas de la ciudad.',
          startDate: 'Año 1040',
          endDate: ''
        }
      ],
      specificData: {
        population: '65.000 habitantes',
        region: 'Costa de las Sombras'
      },
      mapData: { x: 360, y: 340, color: '#4F46E5' },
      color: '#4F46E5',
      notes: 'La ciudad se divide en tres distritos: el Muelle Bajo, el Barrio del Archivo y las Terrazas Altas de Ópalo.',
      createdAt: '2026-08-15T11:45:00.000Z',
      updatedAt: '2026-09-02T14:45:00.000Z'
    },
    {
      id: 'place-distrito-archivo',
      projectId: 'proj-susurro-sombras',
      name: 'Distrito del Archivo',
      category: 'asentamientos',
      type: 'barrio',
      parentId: 'place-puerto-gris',
      description: 'Enclave silencioso de callejuelas empinadas, conventillos eruditos y bibliotecas subterráneas excavadas en la roca viva.',
      tags: ['barrio', 'erudición', 'bibliotecas'],
      status: 'activo',
      history: 'Reservado por decreto real para los transcriptores y notarios de la corona.',
      historicalDates: { foundationDate: 'Año 810', period: '' },
      authorities: [],
      specificData: { function: 'Investigación histórica, preservación y censura' },
      mapData: { x: 350, y: 350, color: '#4F46E5' },
      color: '#4F46E5',
      notes: 'Patrullado día y noche por los centinelas del Velo.',
      createdAt: '2026-08-15T12:00:00.000Z',
      updatedAt: '2026-09-02T15:00:00.000Z'
    },
    {
      id: 'place-archivo-central',
      projectId: 'proj-susurro-sombras',
      name: 'Archivo Central de los Siete',
      category: 'asentamientos',
      type: 'edificio',
      parentId: 'place-distrito-archivo',
      description: 'Complejo laberíntico de piedra basáltica de tres plantas sobre el nivel del suelo y cinco niveles subterráneos abovedados.',
      tags: ['archivo', 'fortaleza', 'manuscritos', 'secreto'],
      status: 'activo',
      history: 'Aquí se custodian los anales del mundo desde antes del Gran Ocaso. Su sótano más profundo fue sellado con plomo en 1015.',
      historicalDates: { foundationDate: 'Año 820', period: 'Más de dos siglos de custodia' },
      authorities: [
        {
          id: 'auth-archivo-elena',
          characterId: 'char-elena',
          title: 'Restauradora y Archivista Principal',
          responsibilityType: 'civil',
          description: 'Responsable de la conservación y cotejo de códices de la cripta oriental.',
          startDate: 'Año 1045',
          endDate: ''
        }
      ],
      specificData: {
        function: 'Depósito documental y preservación de reliquias escritas'
      },
      mapData: { x: 345, y: 355, color: '#4F46E5' },
      color: '#4F46E5',
      notes: 'Lugar donde transcurre la escena inicial del Capítulo 1.',
      createdAt: '2026-08-15T12:10:00.000Z',
      updatedAt: '2026-09-02T15:10:00.000Z'
    },
    {
      id: 'place-palacio-opalo',
      projectId: 'proj-susurro-sombras',
      name: 'Palacio de Ópalo',
      category: 'asentamientos',
      type: 'palacio',
      parentId: 'place-puerto-gris',
      description: 'Solemne mansión señorial de mármol grisáceo y ventanales góticos emplazada en lo más alto de los riscos de Puerto Gris.',
      tags: ['palacio', 'tribunal', 'sede-thorne'],
      status: 'activo',
      history: 'Erigido por la Casa Thorne para simbolizar su hegemonía sobre el tráfico comercial del estrecho.',
      historicalDates: { foundationDate: 'Año 890', period: 'Residencia señorial' },
      authorities: [
        {
          id: 'auth-palacio-cassian',
          characterId: 'char-cassian',
          title: 'Señor del Palacio',
          responsibilityType: 'propietaria',
          description: 'Heredero del linaje Thorne y anfitrión de las sesiones del tribunal.',
          startDate: 'Año 1038',
          endDate: ''
        }
      ],
      specificData: { function: 'Sede judicial y residencia dinástica' },
      mapData: { x: 375, y: 335, color: '#4F46E5' },
      color: '#4F46E5',
      notes: 'En sus salones privados se redactan las órdenes de censura del reino.',
      createdAt: '2026-08-15T12:20:00.000Z',
      updatedAt: '2026-09-02T15:20:00.000Z'
    },
    {
      id: 'place-faro-niebla',
      projectId: 'proj-susurro-sombras',
      name: 'Faro de la Niebla',
      category: 'asentamientos',
      type: 'fortaleza',
      parentId: 'place-costa-sombras',
      description: 'Antiguo bastión y atalaya cilíndrica erigida sobre un espolón rocoso que penetra trescientos metros en el mar tempestuoso.',
      tags: ['faro', 'atalaya', 'mar', 'refugio'],
      status: 'activo',
      history: 'Su linterna de cristal prismático dejó de encenderse con aceite regular hace cincuenta años tras el oscurecimiento.',
      historicalDates: { foundationDate: 'Año 780', period: 'Operativo con intervalos' },
      authorities: [
        {
          id: 'auth-faro-mateo',
          characterId: 'char-mateo',
          title: 'Práctico y Vigía Mayor',
          responsibilityType: 'militar',
          description: 'Encargado del sonar de campanas náuticas y la orientación de navíos entre los arrecifes.',
          startDate: 'Año 1042',
          endDate: ''
        }
      ],
      specificData: { function: 'Vigilancia náutica y refugio de marineros' },
      mapData: { x: 330, y: 370, color: '#4F46E5' },
      color: '#4F46E5',
      notes: 'Punto de encuentro clandestino de Mateo y Elena en el Capítulo 2.',
      createdAt: '2026-08-16T14:00:00.000Z',
      updatedAt: '2026-09-02T15:30:00.000Z'
    },
    {
      id: 'place-montes-umbrios',
      projectId: 'proj-susurro-sombras',
      name: 'Montes Umbríos',
      category: 'naturaleza',
      type: 'cordillera',
      parentId: 'place-oakhaven',
      description: 'Muralla geológica de picos afilados y desfiladeros estrechos que separa la cuenca litoral de los desiertos fríos del interior.',
      tags: ['cordillera', 'montañas', 'frontera-natural'],
      status: 'activo',
      history: 'Barrera infranqueable durante las guerras de invierno.',
      historicalDates: { foundationDate: '', period: '' },
      authorities: [],
      specificData: { altitude: '3.420 m (máx)' },
      mapData: { x: 500, y: 260, color: '#059669' },
      color: '#059669',
      notes: 'En sus laderas anidan aves de presa que no bajan jamás a la niebla.',
      createdAt: '2026-08-16T15:00:00.000Z',
      updatedAt: '2026-09-02T15:45:00.000Z'
    },
    {
      id: 'place-pico-ceniza',
      projectId: 'proj-susurro-sombras',
      name: 'Pico Ceniza',
      category: 'naturaleza',
      type: 'montana',
      parentId: 'place-montes-umbrios',
      description: 'Cumbre más elevada de los Montes Umbríos, perpetuamente cubierta por un manto de nieve negruzca de origen arcaico.',
      tags: ['pico', 'cumbre', 'peligro'],
      status: 'inaccesible',
      history: 'Lugar donde la leyenda sitúa el impacto del fragmento estelar del Ocaso.',
      historicalDates: { foundationDate: '', period: '' },
      authorities: [],
      specificData: { altitude: '3.420 m', hazards: 'Vientos huracanados y congelación instantánea' },
      mapData: { x: 515, y: 245, color: '#059669' },
      color: '#059669',
      notes: 'Nacimiento de los torrentes que alimentan el Río Plata.',
      createdAt: '2026-08-16T15:30:00.000Z',
      updatedAt: '2026-09-02T16:00:00.000Z'
    },
    {
      id: 'place-bosque-susurros',
      projectId: 'proj-susurro-sombras',
      name: 'Bosque de los Susurros',
      category: 'naturaleza',
      type: 'bosque',
      parentId: 'place-oakhaven',
      description: 'Extensión forestal de robles y tejos centenarios donde la niebla se condensa en filamentos fosforescentes.',
      tags: ['bosque', 'antiguo', 'mágico'],
      status: 'activo',
      history: 'Territorio sagrado para las tribus nativas previas a la fundación del reino.',
      historicalDates: { foundationDate: '', period: '' },
      authorities: [],
      specificData: { hazards: 'Desorientación espacial y acústica' },
      mapData: { x: 410, y: 280, color: '#059669' },
      color: '#059669',
      notes: 'Oculta en su corazón las ruinas del Portal del Ocaso.',
      createdAt: '2026-08-16T16:00:00.000Z',
      updatedAt: '2026-09-02T16:15:00.000Z'
    },
    {
      id: 'place-rio-plata',
      projectId: 'proj-susurro-sombras',
      name: 'Río Plata',
      category: 'naturaleza',
      type: 'rio',
      parentId: 'place-oakhaven',
      description: 'Arteria fluvial navegable de aguas frías y cristalinas que desciende desde las cumbres y desemboca en la bahía de Puerto Gris.',
      tags: ['río', 'fluvial', 'comercio'],
      status: 'activo',
      history: 'Vía principal de abastecimiento de madera y cereal durante siglos.',
      historicalDates: { foundationDate: '', period: '' },
      authorities: [],
      specificData: {
        originPlaceId: 'place-pico-ceniza',
        mouthPlaceId: 'place-mar-tinieblas',
        length: '240 km'
      },
      mapData: { x: 440, y: 300, color: '#059669' },
      color: '#059669',
      notes: 'Sus meandros inferiores atraviesan los arrabales de Puerto Gris.',
      createdAt: '2026-08-16T16:30:00.000Z',
      updatedAt: '2026-09-02T16:30:00.000Z'
    },
    {
      id: 'place-mar-tinieblas',
      projectId: 'proj-susurro-sombras',
      name: 'Mar de las Tinieblas',
      category: 'naturaleza',
      type: 'mar',
      parentId: 'place-valdora',
      description: 'Océano austral de aguas gélidas donde la bruma se vuelve impenetrable a partir de la tercera legua náutica.',
      tags: ['mar', 'océano', 'bruma', 'peligro'],
      status: 'activo',
      history: 'Ruta prohibida por el Tribunal tras la desaparición de la Tercera Flota Real en 1030.',
      historicalDates: { foundationDate: '', period: '' },
      authorities: [],
      specificData: { hazards: 'Corrientes traicioneras y pérdida total de visibilidad' },
      mapData: { x: 300, y: 420, color: '#059669' },
      color: '#059669',
      notes: 'Mateo conserva un diario náutico secreto con rumbos seguros para sortear sus bajíos.',
      createdAt: '2026-08-16T17:00:00.000Z',
      updatedAt: '2026-09-02T16:45:00.000Z'
    },
    {
      id: 'place-calzada-ocaso',
      projectId: 'proj-susurro-sombras',
      name: 'Calzada del Gran Ocaso',
      category: 'infraestructura',
      type: 'carretera',
      parentId: 'place-oakhaven',
      description: 'Vía empedrada con losas de basalto negro y petriles fortificados que une los muelles de Puerto Gris con las terrazas del Archivo.',
      tags: ['calzada', 'camino', 'vía-militar'],
      status: 'activo',
      history: 'Construida por ingenieros militares en el siglo IX para permitir el transporte rápido de artillería.',
      historicalDates: { foundationDate: 'Año 850', period: 'En uso continuo' },
      authorities: [],
      specificData: {
        originPlaceId: 'place-puerto-gris',
        destinationPlaceId: 'place-archivo-central',
        distance: '4.5 km',
        transitStatus: 'Vigilada por retenes del Velo',
        controlGroupOrEntity: 'Orden del Velo'
      },
      mapData: { x: 355, y: 348, color: '#D97706' },
      color: '#D97706',
      notes: 'Dotada de farolas de gas de carbón que apenas alumbran diez metros a la redonda.',
      createdAt: '2026-08-16T17:30:00.000Z',
      updatedAt: '2026-09-02T17:00:00.000Z'
    },
    {
      id: 'place-portal-ocaso',
      projectId: 'proj-susurro-sombras',
      name: 'Portal del Ocaso',
      category: 'especiales',
      type: 'portal',
      parentId: 'place-bosque-susurros',
      description: 'Monolito megalítico de piedra meteórica tallado con inscripciones circulares que emiten un tenue resplandor cobrizo en luna nueva.',
      tags: ['portal', 'secreto', 'magia-antigua', 'misterio'],
      status: 'secreto',
      history: 'Resto de una civilización anterior que dominaba el tránsito entre planos.',
      historicalDates: { foundationDate: 'Desconocida', period: 'Era Primigenia' },
      authorities: [],
      specificData: {
        dangerLevel: 'Extremo',
        accessRequirements: 'Medallón de Elena o Llave de los Siete',
        supernaturalEffects: 'Distorsión temporal local y resonancia acústica con manuscritos arcanos'
      },
      mapData: { x: 425, y: 270, color: '#7C3AED' },
      color: '#7C3AED',
      notes: 'La clave final que busca Elena para revertir la niebla que asola el reino.',
      createdAt: '2026-08-16T18:00:00.000Z',
      updatedAt: '2026-09-02T17:30:00.000Z'
    }
  ],
  notes: [
    {
      id: 'note-1',
      projectId: 'proj-susurro-sombras',
      title: 'Naturaleza de la Bruma Perpetua',
      content: 'La niebla no es vapor de agua común: posee densidad variable y amortigua el sonido a partir de los cincuenta metros. Las brújulas pierden precisión en presencia de corrientes frías procedentes del norte.',
      tags: ['mundo', 'investigación', 'magia'],
      placeId: 'place-mar-tinieblas',
      createdAt: '2026-08-15T14:00:00.000Z',
      updatedAt: '2026-08-25T11:00:00.000Z'
    },
    {
      id: 'note-2',
      projectId: 'proj-susurro-sombras',
      title: 'Jerarquía del Concilio de las Sombras',
      content: 'El gobierno está dividido en tres ramas: La Orden del Velo (custodia de la ley y censura), El Gremio de Mareantes (rutas y suministros) y Los Siete Sabios (administración judicial). Cassian responde formalmente ante los Sabios, pero su poder práctico supera al de todos ellos.',
      tags: ['política', 'trama', 'organizaciones'],
      placeId: 'place-palacio-opalo',
      createdAt: '2026-08-17T16:30:00.000Z',
      updatedAt: '2026-08-28T09:00:00.000Z'
    },
    {
      id: 'note-3',
      projectId: 'proj-susurro-sombras',
      title: 'Misterio: El diario del astrónomo ciego',
      content: 'Encontrar una pista en el Capítulo 4 que conecte el diario con la torre derruida al sur del cabo. El astrónomo predijo el día exacto en que la luna volverá a ser visible.',
      tags: ['misterio', 'pista', 'trama'],
      placeId: 'place-faro-niebla',
      createdAt: '2026-08-22T19:00:00.000Z',
      updatedAt: '2026-09-02T14:20:00.000Z'
    }
  ]
};
